apiVersion : apps/v1
kind : Deployment
metadata :
  name : post-depl
spec :
  replicas : 1
  selector :
    matchLabels :
      app : post
  template :
    metadata : 
      labels :
        app : post
    spec :
      containers :
        - name  : post
          image : muhammedmustafa/post
          env :
            - name : NATS_CLIENT_ID
              valueFrom :
                fieldRef :
                  fieldPath : metadata.name
            - name  : NATS_URL
              value : 'http://nats-srv:4222'
            - name  : NATS_CLUSTER_ID
              value : social
            - name  : MONGO_URI
              value : mongodb://post-mongo-srv:27017/post
            - name  : CLOUDINARY_NAME
              value : microservices
            - name  : CLOUDINARY_API_KEY
              value : "811727343751112"
            - name  : CLOUDINARY_SECRET_KEY
              valueFrom :
                secretKeyRef :
                  name  : cloudinary-secret
                  key   : CLOUDINARY_SECRET_KEY
            - name : JWT_KEY
              valueFrom :
                secretKeyRef :
                  name  : jwt-secret
                  key : JWT_KEY
--- 

apiVersion : v1
kind : Service
metadata : 
  name : post-srv
spec :
  type : ClusterIP
  selector :
    app : post
  ports :
    - name : post
      protocol : TCP
      port : 3000
      targetPort : 3000